### ISSUE TITLE
Pull pcre2 from conda-forge

### ISSUE THREAD

**Issue by dfornika** [conda-forge/julia-feedstock#1]
When pcre2 has been accepted into conda-forge, add it as a build-time and run-time requirement

https://github.com/conda-forge/staged-recipes/pull/3656

**Comment by jakirkham** [comment]
Should be good to go now. Though it might be worthwhile to check on how it need to be pinned.

**Comment by tkelman** [comment]
It probably doesn't, as long as it's pcre2. This has been our least problematic dependency over time.

**Comment by jakirkham** [comment]
The pinning is to make sure that we have a version range that is not breaking things. They have changed the SONAME a couple of times FWICT.

**Comment by tkelman** [comment]
We load the unversioned so I believe. I can't recall pcre ever making a change that broke anything on the Julia side, other than minor little build issues.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/julia-feedstock/pull/9 ).

**Comment by jakirkham** [comment]
Related question, does Julia actually link to PCRE2 or does it just use it as part of the build process? Asking as I'm not seeing any linkages when inspecting Julia, but I could just be missing something.

**Comment by tkelman** [comment]
It's dynamically loaded and used at runtime (and build time as well).
