### ISSUE TITLE
Latest Version of Julia

### ISSUE THREAD

**Issue by zzj0402** [conda-forge/julia-feedstock#102]
Please provide the latest version of Julia, instead of just 1.1

**Comment by amandamancini** [comment]
I also need the most recent version of Julia (1.5.3)

**Comment by jakirkham** [comment]
If one of you has time to work on this, that would be fantastic! 😄

**Comment by zzj0402** [comment]
I could work on this. Where to start?

**Comment by jakirkham** [comment]
Thanks for the help! 😄

Would make a fork, update [the version and checksum]( https://github.com/conda-forge/julia-feedstock/blob/b7d22453e14d21b552a5aaca7de68450c89be239/recipe/meta.yaml#L2-L3 ), and submit a PR. Then go from there 🙂
