### ISSUE TITLE
SuiteSparse Compatiblility with Sundials.jl

### ISSUE THREAD

**Issue by mjohnson541** [conda-forge/julia-feedstock#118]
On the new v1.6.1 installing and precompiling Sundials.jl (dependency of DifferentialEquations.jl) gives: 

ERROR: LoadError: InitError: could not load library "/Users/mattjohnson/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib"
dlopen(/Users/mattjohnson/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib, 1): Library not loaded: @rpath/libsuitesparseconfig.5.4.0.dylib
  Referenced from: /Users/mattjohnson/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib
  Reason: image not found

This seems to be due to the suitesparse version choice: https://github.com/SciML/Sundials.jl/issues/303. Building instead with suitesparse 5.4.0 fixes this issue. This might not be an issue after Julia 1.7 in BinaryBuillder it looks like they're planning to move to 5.10.0 for Julia 1.7.

**Comment by mkitti** [comment]
This makes the case for pinning the versions to the versions used upstream if they exist. I'm guessing the official builds work just fine?
