### ISSUE TITLE
julia upgrade: pre-unlink script failed warning

### ISSUE THREAD

**Issue by ngam** [conda-forge/julia-feedstock#137]
```
  - julia                      1.6.4  h2a39549_0              installed                      
  + julia                      1.6.4  h34dcedf_2              conda-forge/linux-64      96 MB
```

```
  - libunwind                  1.6.2  h9c3ff4c_0              installed                      
  + libunwind                  1.5.0  h9c3ff4c_1              conda-forge/linux-64      72 KB
```

```
WARNING conda.core.link:run_script(1228): pre-unlink script failed for package conda-forge/linux-64::julia-1.6.4-h2a39549_0
consider notifying the package maintainer
```

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by mkitti** [comment]
I need more details, although other issues may already contain them.

**Comment by ngam** [comment]
> I need more details

like what?

**Comment by mkitti** [comment]
Is it the same as https://github.com/conda-forge/julia-feedstock/issues/134 ? Is there also a post-link error?

**Comment by ngam** [comment]
No that I am aware of, does the post-link error happening when you add/upgrade the package too?

**Comment by mkitti** [comment]
I have not reproduced this error yet, so no.

**Comment by ngam** [comment]
Closing this, since it is being address by #138
