### ISSUE TITLE
pre-unlink.sh and juliarc.jl are out of date

### ISSUE THREAD

**Issue by mkitti** [conda-forge/julia-feedstock#138]
pre-unlink.sh and juliarc.jl are out of date

pre-unlink.sh refers to `JULIA_PKGDIR` which has been replaced by `JULIA_DEPOT_PATH`
`juliarc.jl` should be now be `~/.julia/config/startup.jl` since Julia v0.7

Going forward the best way to manage conda environments and julia environments would to create a new top-level shared julia environment for each conda environment. This has become easier with certain command line changes:

https://docs.julialang.org/en/v1/NEWS/#Command-line-option-changes

**Comment by ngam** [comment]
```
Executing transaction: - ERROR: KeyError: key "JULIA_PKGDIR" not found
Stacktrace:
 [1] (::Base.var"#509#510")(k::String)
   @ Base ./env.jl:79
 [2] access_env
   @ ./env.jl:43 [inlined]
 [3] getindex(#unused#::Base.EnvDict, k::String)
   @ Base ./env.jl:79
 [4] top-level scope
   @ none:1

WARNING conda.core.link:run_script(1228): pre-unlink script failed for package conda-forge/linux-64::julia-1.6.4-h34dcedf_2
consider notifying the package maintainer
\   Installing known registries into `~/.julia`

```
