### ISSUE TITLE
increase number of cores for testing

### ISSUE THREAD

**Issue by ngam** [conda-forge/julia-feedstock#145]
https://github.com/conda-forge/julia-feedstock/blob/1cbc3c93ce1aa68bdb057ba6f969c8058377ff4d/recipe/meta.yaml#L70-L80

What's the command for using all available cores/threads? I noticed that `julia -e "..."` would use number of threads - 1 (so 8 threads yield 7 workers, etc.)  

@mkitti any ideas?

--- 

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ngam** [comment]
Can we use `julia -e -p ${CPU_COUNT} "..."`?

**Comment by mkitti** [comment]
It depends if you want multiple processes or threads. `julia -t auto` is what I usually use for multithreading, but I think testing is a multiprocessing game. Let me check upstream.

**Comment by ngam** [comment]
> It depends if you want multiple processes or threads. `julia -t auto` is what I usually use for multithreading, but I think testing is a multiprocessing game. Let me check upstream.

Okay. This will make a bit of a difference. Currently the linux64 tests run on 1 processor/thread. The osx64 tests run on 3.

**Comment by mkitti** [comment]
Here's how the Julia is tested at https://build.julialang.org/#/

```
bin/julia -e 'include(joinpath(Sys.BINDIR, Base.DATAROOTDIR, "julia", "test", "choosetests.jl")); Base.runtests(append!(choosetests()[1], ["LibGit2/online", "--skip", "Pkg", "Pkg/pkg"]); ncores=min(Sys.CPU_THREADS, 8, 6))
```

https://github.com/JuliaCI/julia-buildbot/blob/45b3721b4a984d5ab47e9c0be9398e4be01d9d0d/master/separated_testing.py#L18

**Comment by mkitti** [comment]
See also https://docs.julialang.org/en/v1/stdlib/Test/#Base.runtests

**Comment by ngam** [comment]
Okay, thanks. I will look into when we move past the immediate stuff (and get 1.7 and LTS stuff out of the way). Not a big deal for now.

**Comment by ngam** [comment]
Closing for now, let me know if you need any help with the ready PR. Happy to discuss changes, etc.
