### ISSUE TITLE
updates + plan

### ISSUE THREAD

**Issue by ngam** [conda-forge/julia-feedstock#149]
@mkitti 

How about the following plan going forward in order:

1. we need to fix the prelink, etc. problems and investigates more of the issues 
2. we need a separate LTS branch (for 1.6 and its updates)
3. we need to fix the patches, etc. for julia 1.7, and then build for arm and so on (these are ready, but let's not merge yet)

For now keep the 1.7 and libunwind 1.6 PRs open with no action, and let's focus on immediately fixing any problems. Then we open an LTS branch. Then we focus on v1.7. 

What's the latest regarding fixing the linking problems and/or any other issues?

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by mkitti** [comment]
I agree. With 1.6 my objective was to just get things working. With 1.7, we should fix the residual legacy issues before releasing.

Another feature I would to (re)implement, is coupling Julia environments with conda environments.

Additionally for both the 1.6 and 1.7 branches, we should try to add Windows support.

**Comment by ngam** [comment]
Should I start a LTS branch then? I am running into some ambiguous problems with the v1.7 build, it may need some more work.

**Comment by ngam** [comment]
i fixed the issues with the v1.7

**Comment by ngam** [comment]
the arm build will need these to be available as arm. Still long way to go.

```
  - openlibm
  - openblas-ilp64
  - p7zip
```

**Comment by ngam** [comment]
I want to look into this later, so just storing it here for now:

```
WARNING (julia): run-exports library package conda-forge::pcre2-10.37-h032f7d1_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): dso library package conda-forge::mbedtls-3.1.0-h9c3ff4c_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): run-exports library package conda-forge::libssh2-1.10.0-ha56f1ee_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): run-exports library package conda-forge::libgit2-1.1.1-hee63804_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): run-exports library package conda-forge::libnghttp2-1.43.0-h812cca2_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): run-exports library package conda-forge::gmp-6.2.1-h58526e2_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): dso library package conda-forge::libgfortran5-11.2.0-h5c6108e_11 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): run-exports library package conda-forge::arpack-3.7.0-hdefa2d7_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): run-exports library package conda-forge::zlib-1.2.11-h36c2ea0_1013 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): dso library package conda-forge::openlibm-0.7.0-h516909a_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): dso library package conda-forge::p7zip-16.02-he1b5a44_1000 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (julia): run-exports library package conda-forge::mpfr-4.1.0-h9202a9a_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)

```

**Comment by mkitti** [comment]
Feel free to push through. I will be around to help, but you may have more time to work on this than I.

**Comment by ngam** [comment]
Okay, I don't think I will be able to push on the front of arm64 stuff yet. Will have to wait for the bots to push through the deps. 

We can focus on Windows next if you'd like.

Do you think all these dependencies are needed still? They seem a bit excessive or maybe I am missing something...

**Comment by mkitti** [comment]
With the above dependencies, I am not clear what is meant by these not being used. Julia does not necessarily dynamically load all the shared libraries at startup. It's also possible we have a build misconfiguration and Julia is actually still using it's own vendored copy from BinaryBuilder.
