### ISSUE TITLE
packaging Julia packages for conda-forge

### ISSUE THREAD

**Issue by ngam** [conda-forge/julia-feedstock#165]
My second concern is that it is not completely clear to me to what degree this PR really addresses the issues it closes. For example, #14 is about packaging Julia packages for conda-forge, i.e. how should I create the conda-forge feedstock `julia-rainfarm` from https://github.com/jhardenberg/RainFARM.jl. While sorting out the depot paths certainly helps and might be necessary, from reading this PR I still don't know how to do this or where to look up the documentation. In terms of documentation, at a minimum I would expect a bullet point in the [enumeration for new packages](https://conda-forge.org/docs/maintainer/adding_pkgs.html#getting-started).

This is probably beyond the scope of this PR, but in that case we might want to keep #14 open for now.

_Originally posted by @zklaus in https://github.com/conda-forge/julia-feedstock/issues/157#issuecomment-1003643656_

**Comment by isuruf** [comment]
Keeping #14 open
