### ISSUE TITLE
JULIA_SSL_CA_ROOTS_PATH= ?

### ISSUE THREAD

**Issue by ngam** [conda-forge/julia-feedstock#201]
```
  GitError(Code:ERROR, Class:SSL, Your Julia is built with a SSL/TLS engine that libgit2 doesn't know how to configure to use a file or directory of certificate authority roots, but your environment specifies one via the JULIA_SSL_CA_ROOTS_PATH variable. If you believe your system's root certificates are safe to use, you can `export JULIA_SSL_CA_ROOTS_PATH=""` in your environment to use those instead.)

```

While extending the testing, I got this error. In our activation script, we have it pointing somewhere else (`$CONDA_PREFIX/ssl/cacert.pem`)

https://github.com/conda-forge/julia-feedstock/blob/9f1e439c4717c39c92815956b1408f6e5aae79a8/recipe/scripts/activate.sh#L16-L18

I wonder if we should revisit this? @mkitti will know best perhaps

_Originally posted by @ngam in https://github.com/conda-forge/julia-feedstock/issues/200#issuecomment-1059384531_

**Comment by mkitti** [comment]
This error was not occurring before. I wonder if we are now having issues with mbedtls / libgit2 / libssh2 since I think we did manage to upgrade that axis in Julia 1.8.

**Comment by ngam** [comment]
I started exporting it as `JULIA_SSL_CA_ROOTS_PATH=""` for testing. It seems to work locally. 

Also, besides tests associated with this failing, I believe we have a few more. They seem to be trivial:
1. checking version numbers (obviously we will have some issues there)
2. checking julia-vendored libunwind (obviously we will have issues there)

There might be one or two stray tests that need correcting, but basically we may be able to run the whole test suite without errors. Our linux-64 CI breaks down tho during the testing, likely memory/etc issues. I will try to run it without all cores to see if that helps.

I am gonna patch those tests and see how things will look like :)

**Comment by ngam** [comment]
> This error was not occurring before. I wonder if we are now having issues with mbedtls / libgit2 / libssh2 since I think we did manage to upgrade that axis in Julia 1.8.

I don't think we were testing for this particular thing before. This error happens only when running tests of `Pkg`, which I believe we didn't do before.

Also: As far as I could tell, we are now able to get *all tests* to pass with the appropriate patches. Nothing in the newly added patch actually is substantial (it just comments out testing exact versions of libraries). I am now moving on to usage testing (hence #202). We can also likely move all deps to in-house in the very near future (LLVM, etc.) but I am not sure yet --- waiting to see what people at homebrew, etc. come up with.

**Comment by ngam** [comment]
An example of all tests passing: https://github.com/conda-forge/julia-feedstock/pull/200 (only on osx-64; linux-64 times out --- seems like a much weaker CI anyway)
