### ISSUE TITLE
Add `osx-arm64` support? (Julia 1.8.0 now supports M1)

### ISSUE THREAD

**Issue by jmuchovej** [conda-forge/julia-feedstock#226]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Julia isn't installable on ARM-based MacOS. If helpful, I know that PyTorch has ARM support [(this Azure Pipeline)][pytorch-azure] and Python also has ARM support [(this Azure Pipeline)][python-azure].

[pytorch-azure]: https://github.com/conda-forge/pytorch-cpu-feedstock/blob/2a3f37bc0b07be6ca46401c2381c39b6eeb1d28b/.azure-pipelines/azure-pipelines-osx.yml
[python-azure]: https://github.com/conda-forge/python-feedstock/blob/134ba25ba2f5696c14060518fafb4aaebfedb544/.azure-pipelines/azure-pipelines-osx.yml

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by jmuchovej** [comment]
Whoops. I didn't see the open PRs:
- https://github.com/conda-forge/julia-feedstock/pull/219
- https://github.com/conda-forge/julia-feedstock/pull/224

**Comment by mkitti** [comment]
Unfortunately it's a bit complicated. We are closer to this than we have been. The main complication is how to cross-compile the system image. I am contemplating a way to deliver Julia without the system image and then provide the user a way to build it themselves.

As a practical matter, I would consider using `juliaup` in the meantime: https://anaconda.org/conda-forge/juliaup

`juliaup` can be installed via conda-forge. `juliaup` can then install `julia`. You may want to consider stealing the activation and deactivation scripts from this repository.

Thank you for your interest @jmuchovej

**Comment by jmuchovej** [comment]
👋 @mkitti thanks for the quick response! I've never used `juliaup`, but will definitely do this, for now.

Maybe a question to post over there, but... would using `juliaup` in a `conda` environment be equivalent to using a local `poetry` environment (for Python) or regular `npm install` (instead of `npm install -g`)? Another way to think of this is... does `juliaup` add Julia version management atop what you "already get" by using `conda` environments?

Also – should we leave this open, since it's ongoing and folks might do like me and check open PRs as an afterthought? (Compared to checking issues.)

**Comment by mkitti** [comment]
To be clear, no Julia packages currently exist within conda-forge. Whether you use this feedstock or juliaup, conda-forge is not tracking Julia dependencies directly.

The closest we have come to directly managing a Julia package is SymbolicRegression.jl in https://github.com/conda-forge/pysr-feedstock/pull/43
