### ISSUE TITLE
bitarray test slow

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/julia-feedstock#23]
Frequently the `bitarray` test takes too long to complete on the CIs. A sample build log is linked below. Is there something we can do to fix this? Should we just skip it?

ref: https://circleci.com/gh/conda-forge/julia-feedstock/62

**Comment by tkelman** [comment]
Shouldn't take much more than a minute on Julia 0.5 - https://travis-ci.org/JuliaLang/julia/jobs/275261992#L1823

Something about the way things are built here may be resulting in a serious performance regression.

**Comment by jakirkham** [comment]
Are there any important options that we should be providing? Do we need to explicitly add `-O2` or `-O3` for instance?

**Comment by tkelman** [comment]
Does the conda build environment set variables like CFLAGS, CXXFLAGS to any default values? Those might be overriding the settings in the Julia build system.

**Comment by jakirkham** [comment]
Yes we set these. What should be looking to add.

**Comment by tkelman** [comment]
What are they set to? Julia will set some defaults (I forget whether it's O2 or O3, would have to check the makefiles), but if they are set to something different in the environment it'll use that value.

**Comment by isuruf** [comment]
Just `-m64`

**Comment by jakirkham** [comment]
Details are [here]( https://github.com/conda-forge/toolchain-feedstock/blob/master/recipe/activate.sh ).

Yes we are not adding any optimizations by default. That is too hairy. Best to be dealt with on a per package basis.

**Comment by jakirkham** [comment]
Any more details on what sort of flags should be added?

**Comment by jakirkham** [comment]
TBH if I run this test locally with our `julia` package, it takes less time than the Travis CI build linked (results below). So I don't think it is a build option issue. However the fact that this test takes wildly different lengths of time to run is disconcerting to say the least.

```
$ julia -e 'Base.runtests(["bitarray"]);'
Test (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
bitarray (1)  |   67.55  |  1.26  |  1.9 | 2821.37    | 343.90  

Test Summary: |   Pass   Total
  Overall     | 890969  890969
    SUCCESS
```

Though I would not be surprised if the test is highly demanding and is causing the CI worker to freeze. Is there some way we can make this test better behaved? If not, I'm leaning towards skipping it as this is slowing down development of the recipe.

**Comment by tkelman** [comment]
It can also depend on which tests run in the same test worker.

**Comment by tkelman** [comment]
> Any more details on what sort of flags should be added?

Build Julia in a totally clean environment from a clone and make. Use the same options that does. Probably does O2 or O3 most places.

**Comment by ngam** [comment]
Closing this, reopen if more discussion is needed. bitarray is still a bit slow, but we improved things by forcing the tests to run in parallel in the #157
