### ISSUE TITLE
warning: parsing line table prologue at ... should have ended at ... but it ended at ...

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/julia-feedstock#24]
Have been seeing a bunch of [warnings]( https://github.com/conda-forge/julia-feedstock/pull/7#issuecomment-329283460 ) when Julia errors on something (copied example below). Not entirely sure what the cause is at this time, but it looks like it is coming from LLVM.

```
julia> akljdsfl
warning: parsing line table prologue at 0x0000e1c8 should have ended at 0x0000e52f but it ended at 0x0000e284
warning: parsing line table prologue at 0x00003c27 should have ended at 0x00003ffc but it ended at 0x00003ce3
warning: parsing line table prologue at 0x0001cd5c should have ended at 0x0001d0f0 but it ended at 0x0001ce25
warning: parsing line table prologue at 0x000086e2 should have ended at 0x00008ae4 but it ended at 0x000087ef
warning: parsing line table prologue at 0x0000a9c0 should have ended at 0x0000ace8 but it ended at 0x0000aa7c
ERROR: UndefVarError: akljdsfl not defined
```

**Comment by jakirkham** [comment]
Should add we tried to ignore prefixes in the binary executables with PR ( https://github.com/conda-forge/julia-feedstock/pull/19 ), but that did not fix the issue. So something else is going on here.

**Comment by tkelman** [comment]
Does it happen in the build-tree version of julia?

**Comment by jakirkham** [comment]
Sorry, are you meaning `master`? If so, haven't tested that. Could try.

That said, we are not sure if this issue is blocking 0.6.0 ATM. So it may be `master` won't work for the same reason. Though this is purely speculative.

**Comment by tkelman** [comment]
No, I mean the compiled julia before it gets packaged by conda. If this warning happens in your build of 0.5.2 I'd consider this "beware, do not use" worthy until it's fully debugged.

**Comment by tkelman** [comment]
I'd also try running julia-debug or enabling assertions in julia and/or llvm.

**Comment by jakirkham** [comment]
That's a good question. Raised the idea in another thread, but haven't followed up on it. Will look into it.

Yeah it's a disconcerting warning. Hence the issue. 😉 I remain hopeful that we can resolve it though.

Thanks for the tips. Will give the debug version a try. How do we go about enabling the debug version of LLVM? Is there a flag we pass to Julia (since we are using Julia's build of LLVM)?

**Comment by isuruf** [comment]
This is definitely a conda-build bug. I tried locally and I get this warning, but when I tried in a conda environment with the path length exactly 256, I don't get this warning.

**Comment by isuruf** [comment]
cc @msarahan

**Comment by isuruf** [comment]
Btw, in #19, you tried ignoring prefixes in the executables, but it's not the executable that's the problem, it's `libjulia.so` which stores the prefix. I checked by running the executable in long prefix with library in short prefix using LD_PRELOAD and there are warnings. Running the executable in short prefix with library in long prefix gives no warnings.

**Comment by isuruf** [comment]
Probably related to https://github.com/conda/conda-build/issues/1674

**Comment by tkelman** [comment]
Good catch. As long as you don't change the relative layout, you don't need to rewrite that particular string, the binaries should be relocatable on their own.

**Comment by jakirkham** [comment]
Thanks for the diagnosis @isuruf. Was wondering if changing hard coded paths elsewhere might fix it. Do you have any idea where the prefix is coming from? I'm not aware of a similar issue with `llvmdev`. So am wondering if it is coming from something else (maybe Julia itself?).

**Comment by isuruf** [comment]
I don't know, but the paths are gcc's include path and `crt1.o` which are not found anyways at runtime.

**Comment by jakirkham** [comment]
Interesting. So may this be fixed by simply not relying on the `gcc` package then?

**Comment by isuruf** [comment]
Not really. then it will use the `gcc` from the container and the path there will be used. We just have to tell conda to not do any replacements in `libjulia.so` and `bin/julia`

**Comment by isuruf** [comment]
Ah, I see what you are saying, conda will not do that since gcc is not in `PREFIX`

**Comment by jakirkham** [comment]
Admittedly it is still a problem if we switch back to a compiler that will be in the `PREFIX`. So we probably should still do as you suggest and add the library to the `ignore_prefix_files` lest we forget about this issue later.

**Comment by jakirkham** [comment]
AFAICT PR ( https://github.com/conda-forge/julia-feedstock/pull/26 ), which switches to the system compiler, does not have any hard coded paths detected as evidenced by this [build]( https://circleci.com/gh/conda-forge/julia-feedstock/68 ). One can see this by searching for `Detected hard-coded path in binary file`. Compare this to the [last build on `master`]( https://circleci.com/gh/conda-forge/julia-feedstock/67 ), which has several detected. So if this is the issue, that PR should fix it.

**Comment by jakirkham** [comment]
Looks like PR ( https://github.com/conda-forge/julia-feedstock/pull/26 ) builds without triggering this warning in the test suite at all. As this was a very regular warning, guessing that means the aforementioned PR will fix it.
