### ISSUE TITLE
Update to 1.9.0?

### ISSUE THREAD

**Issue by PallHaraldsson** [conda-forge/julia-feedstock#246]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I saw where in the repo and would make a PR, just not sure about the SHA.

### Installed packages

```shell
?
```

### Environment info

```shell
?
```

**Comment by mkitti** [comment]
Can you submit a pull request to fix the patches?

**Comment by PallHaraldsson** [comment]
I coundn't even find the older sha, not sure where to look, I didn't find it here:

**Comment by mkitti** [comment]
We pull the source from https://github.com/JuliaLang/julia/releases/download/v1.8.5/julia-1.8.5-full.tar.gz and calculate the sha256 sum directly.

```
$ curl -L https://github.com/JuliaLang/julia/archive/refs/tags/v1.8.5.tar.gz 2>/dev/null | sha256sum
66602534f36dc7e096228369af57ed8f70b3b98600c51e3364a5d89a5f78ba34  -
```

We probably should be pulling the source from here though:
https://github.com/JuliaLang/julia/releases/download/v1.8.5/julia-1.8.5-full.tar.gz

**Comment by PallHaraldsson** [comment]
$ curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.0-linux-x86_64.tar.gz | sha256sum
00c614466ef9809c2eb23480e38d196a2c577fff2730c4f83d135b913d473359  -

Note, not same as for, so do not use SHA from that message:
$ curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.0-linux-x86_64-full.tar.gz
> [..] The specified key does not exist.</Message><Key>bin/linux/x64/1.9/julia-1.9.0-linux-x86_64-full.tar.gz [..]

**Comment by PallHaraldsson** [comment]
Mhh, missed that PR, that's still not merged. It has different SHA, I sill close my stuff.
