### ISSUE TITLE
BUG: libstdc++.so.6 linkage issue

### ISSUE THREAD

**Issue by MilesCranmer** [conda-forge/julia-feedstock#253]
All of my CI tests on Ubuntu + Conda seem to be failing with a library linkage issue:

```
Run python -m pysr.test main
ERROR: Unable to dlopen(cxxpath) in parent!
Message: /usr/share/miniconda3/envs/pysr-test/lib/python3.10/site-packages/scipy/sparse/../../../../libstdc++.so.6�E6W: cannot open shared object file: No such file or directory
Error: Process completed with exit code 1.
```

Here is an example run: https://github.com/MilesCranmer/PySR/actions/runs/5171734252

I had initially thought this was a scipy issue from the pathname, but the error message actually looks to be from this line in the Julia source: https://github.com/JuliaLang/julia/blob/f407a4cac3d1c660d1f8f1a9b367eec108d98178/cli/loader_lib.c#L456, so now I'm not so sure.

A strange thing is that I have actually successfully run the unit tests on Julia 1.9 in the past: https://github.com/MilesCranmer/PySR/actions/runs/5163099602. It's only the past day where they started to break.

Here are the dependencies that changed from 2 days ago (working) to 1 day ago (broken across all Python versions):

```diff
<     libgfortran-ng-12.2.0      |      h69a702a_19          22 KB  conda-forge
>     libgfortran-ng-13.1.0      |       h69a702a_0          23 KB  conda-forge

<     libgfortran5-12.2.0        |      h337968e_19         1.8 MB  conda-forge
>     libgfortran5-13.1.0        |       h15d22d2_0         1.4 MB  conda-forge

<     libssh2-1.10.0             |       hf14f497_3         234 KB  conda-forge
>     libssh2-1.11.0             |       h0841786_0         265 KB  conda-forge

<     libstdcxx-ng-12.2.0        |      h46fd767_19         4.3 MB  conda-forge
>     libstdcxx-ng-13.1.0        |       hfd8a6a1_0         3.7 MB  conda-forge
```

**Comment by JacksonBurns** [comment]
We have also run into this issue over on RMG-Py, see [here](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2455).

**Comment by mkitti** [comment]
Can someone generate a minimum working example (MWE)?

**Comment by mkitti** [comment]
Maybe we should try rebuilding Julia with USE_SYSTEM_CSL=1 ?

**Comment by MilesCranmer** [comment]
Should I close it since we fixed the Conda.jl issue?

**Comment by JacksonBurns** [comment]
This has been resolved for us.

**Comment by MilesCranmer** [comment]
The Conda.jl fix you mean? Or limiting libstdcxx?

**Comment by mkitti** [comment]
Closing since https://github.com/JuliaPy/Conda.jl/pull/241 resolves the issue.
