### ISSUE TITLE
Skip building HTML docs

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/julia-feedstock#27]
Seems that Julia is building the HTML docs as part of the build by default. Not sure that we want to include these. Pretty easy to find them online or download them. Also doubt that someone go looking for them in the `conda` package. Further this step involves creating a Python `virtualenv` environment, downloading a bunch of dependencies, and then doing this build. Seems like that time could be better spent. That said, it is not totally clear how to skip this step except for patching the `Makefile` or letting it run through and deleting the docs after the fact. Would be good to figure out the best way to approach this.

**Comment by jakirkham** [comment]
One option (a bit of a hack) is to truncate `"${SRC_DIR}/doc/Makefile"` and add an empty `default` target (e.g. `echo "default:" > "${SRC_DIR}/doc/Makefile"`). This way when Julia goes to build the docs it can run `make` with a `default` target, but nothing happens. Even though this is a hack, it is relatively robust as it only depends on Julia's source tree's structure, but not so much on its content.

**Comment by jakirkham** [comment]
Any thoughts on how to best approach this, @tkelman?

**Comment by jakirkham** [comment]
For now have put together a hack in PR ( https://github.com/conda-forge/julia-feedstock/pull/32 ), which seems to work. Though if there is a formal way to accomplish this, would be interested in hearing about it.

**Comment by tkelman** [comment]
We've had complaints every time it's been proposed to not include an offline copy of the docs. Would leave them in, or at least make it available as a subpackage.

**Comment by jakirkham** [comment]
It's not typical to include the docs in `conda` packages. We have left in things like the `man` page, which is typically used. However its hard to justify building the HTML docs as they take a while to build, take up a fair bit of space, and do iffy things like install `virtualenv` with `pip` from our `conda` environment. Would rather use this same CI time to run a few more tests on the already time limited Travis CI build. If there is demand, would be willing to discuss a subpackage, but for me personally I'm far more interested in making sure the Julia package works ok on more platforms than worrying about the docs.
