### ISSUE TITLE
Require libuv

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/julia-feedstock#28]
One of Julia's requirements is `libuv`, which we already have packaged at conda-forge. Would be good to make use of our `libuv` instead of allowing it to build its own.

**Comment by jakirkham** [comment]
It looks like there are still some patches being applied to Julia's `libuv`, which make it different from upstream's. Appears some patches have landed and others are open. That said, I don't have a great idea from a cursory look through to what extent it would be possible to use upstream's `libuv` instead of Julia's. Would be good if someone closer to what is going on could share some info.

**Comment by ViralBShah** [comment]
Julia's libuv is a fork. Upstream hasn't accepted our patches for a very long time.
