### ISSUE TITLE
Suggestion to use the pre-built julia binaries

### ISSUE THREAD

**Issue by ViralBShah** [conda-forge/julia-feedstock#41]
I would like to make a suggestion. Instead of building from source, is it possible for this package to use the binaries provided by the julia project? We go through a lot of effort in patching and producing julia binaries that work on all platforms correctly.

Thus just downloading these binaries from julialang.org and untarring them would give the most reliable installation of Julia that is possible for the upstream to support.

**Comment by jakirkham** [comment]
As was [stated in the PR that added `julia`]( https://github.com/conda-forge/staged-recipes/pull/3503#issuecomment-322524410 ), conda-forge's objective is to build packages from source.

**Comment by ViralBShah** [comment]
Thank you for the pointer.
