### ISSUE TITLE
Build failures due to libgit2/SSL error

### ISSUE THREAD

**Issue by dfornika** [conda-forge/julia-feedstock#45]
I've been unable to build this recipe locally (CentOS 7, conda-build 2.1.18) due to julia's libgit2 failing to connect to github over HTTPS with an 'invalid certificate' error.

Possibly related issues:

https://github.com/JuliaLang/julia/issues/13399
https://github.com/JuliaLang/julia/issues/17789
https://github.com/JuliaLang/julia/issues/15128

Possibly related to this commit:

https://github.com/JuliaLang/julia/commit/87913c6c6f518fd8c54002ca437d1fd8de8854f3

**Comment by jakirkham** [comment]
Maybe this [comment]( https://github.com/conda-forge/mosfit-feedstock/issues/23#issuecomment-349016207 ) helps.

**Comment by mbargull** [comment]
xref: https://github.com/bioconda/bioconda-recipes/pull/7818#issuecomment-366390452
> For reference: https://github.com/conda/conda-build/pull/2142 was backported to `conda-build 2.1.18` but https://github.com/conda/conda-build/pull/2259 was not. That introduced the bug from https://github.com/conda/conda-build/issues/2255 into `conda-build 2.1.x`.

**Comment by dfornika** [comment]
Thanks again @mbargull for resolving this issue.

**Comment by mbargull** [comment]
For prosperity, this is the change I [added to `build.sh`](https://github.com/bioconda/bioconda-recipes/blob/68e8b620728059ebb75bf1366e225dd41df3902d/recipes/mentalist/0.1.3/build.sh#L3-L6):

```bash
# circumvent a bug in conda-build >=2.1.18,<3.0.10
# https://github.com/conda/conda-build/issues/2255
[[ -z $REQUESTS_CA_BUNDLE && ${REQUESTS_CA_BUNDLE+x} ]] && unset REQUESTS_CA_BUNDLE
[[ -z $SSL_CERT_FILE && ${SSL_CERT_FILE+x} ]] && unset SSL_CERT_FILE
```
