### ISSUE TITLE
Question: Why PREFIX and not CONDA_PREFIX?

### ISSUE THREAD

**Issue by krinsman** [conda-forge/julia-feedstock#56]
This isn't really an issue, just a question: in the build script of the recipe, the environment variable `PREFIX` appears to be used to refer to the directory of the current conda environment.

However, I thought that the corresponding environment variable is `CONDA_PREFIX`. At the very least, when I do something like `conda activate test`, then `echo $PREFIX` leads to no output, but `echo $CONDA_PREFIX` gives the directory of the conda environment.

Is this perhaps a platform-specific issue? I am on Mac OS X, not Linux. (Although this is also true on the Linux workstation where I work.)

To be honest I don't really understand the relevant conda documentation on the issue: 

https://conda.io/docs/user-guide/tasks/build-packages/environment-variables.html

> PREFIX | Build prefix to which the build script should install.
> CONDA_PREFIX | The path to the conda environment used to build the package, such as /path/to/conda/env. Useful to pass as the environment prefix parameter to various conda tools, usually labeled -p or --prefix.

My hope was that you might be able to clarify this in the context of the build script for this recipe.

**Comment by krinsman** [comment]
Is the difference that $PREFIX is only defined within "the scope of the build script" (i.e. the subshell executing the script, if there is a subshell that executes it), and thus is a "local variable",

whereas $CONDA_PREFIX is a "global variable"? Which is why it is listed under a section called "inherited environment variables"? (Because global variables are "inherited" by the local scope.) 

This would also explain the warning,

> NOTE: Inheriting environment variables can make it difficult for others to reproduce binaries from source with your recipe. Use this feature with caution or avoid it.

correct?

**Comment by jakirkham** [comment]
For generic `conda`/`conda-build` questions, please raise them on the appropriate issue trackers.

ref: https://github.com/conda/conda/issues
ref: https://github.com/conda/conda-build/issues

**Comment by krinsman** [comment]
@jakirkham So this means that the reason why PREFIX is used instead of CONDA_PREFIX in _this_ build script (which was what the question was intended to be about)

reduces to the same reason why anyone would ever use PREFIX instead of CONDA_PREFIX ever in any build script?

(That’s why this is a general conda question, right? Or is there another reason?)

**Comment by jakirkham** [comment]
Correct.
