### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by t-makaro** [conda-forge/julia-feedstock#57]
I've started to look at setting up ijulia on windows, and this would be a really nice option to help get Julia considering that I already use conda.

**Comment by dfornika** [comment]
Hi @t-makaro. Thanks for filing this issue. Unfortunately the build process for julia is fairly complex, so it may be some time before a Windows build is available. We're still working out some issues with the linux & macOS builds at this point.

Are you able to use the official Windows binaries? https://julialang.org/downloads/

**Comment by ngam** [comment]
Closing this, please follow in #162
