### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/julia-feedstock#6]
Not sure all what this will entail, but would be great if we could package 0.6.0 as well. If we want to support multiple versions (e.g. 0.5 and 0.6), we can create a branch for `0.5` that can see continued maintenance and just add 0.6.0 to `master`.

**Comment by dfornika** [comment]
I've created a `v0.5` branch. I closed the other two pull requests and re-opened them against the `v0.5` branch. I've created a new pull request against `master` that is incremented to `v0.6.0`

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/julia-feedstock/pull/7 ).
