### ISSUE TITLE
Conda Installs old version of Julia 1.0.0 instead of Julia 1.0.2

### ISSUE THREAD

**Issue by Fredo-XVII** [conda-forge/julia-feedstock#64]
Hello,

When I install the Julia package with conda (instructions in the site below), conda installs Julia 1.0.0, even though it says 1.0.2 on the package website. See below.

https://anaconda.org/conda-forge/julia

There are some important fixes in the new version, can you update the package to the current version? Can you make it so that I can use conda update julia so that it updates to the current version? Otherwise, I am going to have remove the current install and that has cause issues in the past where I have to remove the entire miniconda installation.

Thanks,

Alfredo

**Comment by dfornika** [comment]
Hi @Fredo-XVII ,

Are you installing into an isolated conda environment, or into the root environment? If possible, I'd recommend creating an environment, something like this:

```
conda create --name julia-1.0.2 julia=1.0.2
```
You can choose another name if you'd like:

```
conda create --name my_env julia=1.0.2
```

Then use `conda activate my_env` to start using your environment.

If you do this then it's less likely that you'll need to remove your entire miniconda installation. The environment is created in a single directory that can be removed and re-built if needed.

Would that work for you?

**Comment by Fredo-XVII** [comment]
Hello,

That might be a solution once the issue is fixed.  Most importantly, I need Julia 1.0.2 to install when I run "conda install -c conda-forge julia", instead of version 1.0.0.  This is the main issue I am currently having.

**Comment by dfornika** [comment]
When I run `conda install -c conda-forge julia` on my machine, it pulls Julia 1.0.2:

```
$ conda install -c conda-forge julia
Solving environment: done

## Package Plan ##

  environment location: /home/dfornika/miniconda3/envs/julia-testing

  added / updated specs: 
    - julia


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    julia-1.0.2                |blas_openblashfe40789_0        53.2 MB  conda-forge

The following NEW packages will be INSTALLED:

    arpack:          3.5.0-blas_openblas_202         conda-forge [blas_openblas]
    blas:            1.1-openblas                    conda-forge
    ca-certificates: 2018.11.29-ha4d7672_0           conda-forge
    curl:            7.63.0-h74213dd_0               conda-forge
    fftw:            3.3.8-h470a237_1                conda-forge
    gmp:             6.1.2-hfc679d8_0                conda-forge
    julia:           1.0.2-blas_openblashfe40789_0   conda-forge [blas_openblas]
    krb5:            1.16.2-hbb41f41_0               conda-forge
    libcurl:         7.63.0-hbdb9355_0               conda-forge
    libedit:         3.1.20170329-haf1bffa_1         conda-forge
    libgcc:          7.2.0-h69d50b8_2                conda-forge
    libgcc-ng:       7.2.0-hdf63c60_3                conda-forge
    libgfortran:     3.0.0-1                         conda-forge
    libgit2:         0.27.7-h5ee2e84_0               conda-forge
    libssh2:         1.8.0-h5b517e9_3                conda-forge
    libstdcxx-ng:    7.2.0-hdf63c60_3                conda-forge
    metis:           5.1.0-hfc679d8_3                conda-forge
    mpfr:            4.0.1-h16a7912_0                conda-forge
    ncurses:         6.1-hfc679d8_2                  conda-forge
    openblas:        0.2.20-8                        conda-forge
    openlibm:        0.5.4-h470a237_0                conda-forge
    openspecfun:     0.5.3-h26a2512_0                conda-forge
    openssl:         1.0.2p-h470a237_1               conda-forge
    pcre2:           10.23-2                         conda-forge
    suitesparse:     4.5.6-blas_openblash55dcaef_201 conda-forge [blas_openblas]
    tbb:             2019.3-h2d50403_0               conda-forge
    tk:              8.6.9-ha92aebf_0                conda-forge
    zlib:            1.2.11-h470a237_3               conda-forge
```

**Comment by Fredo-XVII** [comment]
Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home_dir/XXXXX/.anaconda

  added / updated specs:
    - julia


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    julia-1.0.2                |blas_openblashfe40789_0        53.2 MB  conda-forge
    conda-4.5.12               |        py37_1000         654 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        53.8 MB

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0                              --> 2018.11.29-ha4d7672_0         conda-forge
    certifi:         2018.11.29-py37_0                         --> 2018.11.29-py37_1000          conda-forge
    conda:           4.5.11-py37_0                             --> 4.5.12-py37_1000              conda-forge
    julia:           1.0.0-blas_openblashfe40789_0 conda-forge [blas_openblas] --> 1.0.2-blas_openblashfe40789_0 conda-forge [blas_openblas]
    openssl:         1.0.2p-h14c3975_0                         --> 1.0.2p-h470a237_1             conda-forge

It is working now! You can see the Julia 1.0.0 that I installed recently is being updated to 1.02.

Thanks for checking and helping!! I will close and comment.

Really appreciate it.
